### PR TITLE
[WIP] Minor adds to dining activity PR

### PR DESCRIPTION
**Pull request by genkimarshall**
Don't merge yet :P
Just seeing what I can find. As always, totally open to any input on the commits.

### CODE REVIEW

**Comment by genkimarshall** [comment]
Also, when you look at the preview for fragment_dining_location.xml, do you get a Rendering Error as well? I'm sure it's related to [this](http://stackoverflow.com/questions/26830686/android-recyclerview-error/29289673#29289673) which points to [this issue](https://code.google.com/p/android/issues/detail?id=72117), but I just upgraded to the [most recent canary version](http://tools.android.com/download/studio/canary/latest) which says it was released on March 25th, so according to the last comment in the issue report, it should have the fix. So, just thought I'd ask.

**Comment by genkimarshall** [comment]
So, android:windowContentTransitions is only for API >= 21, so from what I read, it seems that  68d8999 makes it so the default is in the values/ directory, and any phone on API >= 21 will use any values in the values-v21/ directory after loading in the default. Could you please confirm this works on your phone?

**Comment by lidavidm** [comment]
Looks good, but there's merge conflicts (I think I also did stuff with the imports). Run `git merge diningactivity` (make sure that branch is up-to-date) with this branch checked out.

**Comment by lidavidm** [comment]
Or, I can merge these changes into my branch. I'll just do that.

**Comment by genkimarshall** [comment]
Sounds good.

**Pull request merged**
